sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        CBd/L6ttnRc29rQatArWkhnyxezzEuRRQQj9klgh1fydD6EIwxV45oRUcycB76zg5NhH89vRZWTRgRUYO8Gu1mQET/4eIUY+zEfuc1qN1dA1R79i/3ib81tor7ezaY6KQxR6Y78BOGqU+eAMDO7G08P6GmPUD7fXw6m+gmotAgSL9fAQIOc+IzAc4kQlXbra+aSWQNo4p4aKEyDDv61RqarMY5TRb1VlOvpf/SXXU1BVbOZTvRlBRu6slu/zNbXwcSZYkQLNm2Jw0pd1ZaPgk0XCkf2RKeA4MAQ221QxRVme8rejHHXt25PoQ6EI4dpxuHjziW85m4u04iC2SECCsREc/btjUqvTBrAyzIQw9sjaXgdI568Wd9d8e3IvjMSE+oIteI/t3cHH9CbDN7ikWcWZhMUY5dN1q9JgC2JosmFyQVkqHxF4jqUzmC4Nui4ECVZi32rPGKvIHFOARjjciWoSjlsr96S/vqK4A+rzqxCpkb/NfIc4WbqD+mYoPMsdme7OzC5hhvTEdODd9XPTP/vjDI0wMmfHYHezbsJSN9/KwZbByAfHLxgJ7Sgij1V0HU4A1EEcSq+J5cAY1/cSi8FKWQT4NQTctucNHQnh4quu5H8A7RZcoBIZbulqcgHfQhpmQ91wkEZpKK/qgay0LoIBdheQ1rl0jKsmU3ohyKc=
    - secure: >-
        Z0xEeAKGdWWD+3hdymBK0sTTyWvnfBCJXX1OUtNL24ftiUoHds2nuaP1KvdGwlM099lJ4lnoi6AehpHHxBl85X/S40Gofv8vdXWi/qwruDD44wDbJjbS+zQdn1cyJf/YVlbV8zSxzWYJJx//CgBBb7L+6YsPPSQh7pOsrbbEGagBPvjXj4wi4hAuj0jMJTBPouIi8JVSCuzVVcqGlrcke0g5UCHZzZCd/xXnmUSh0WNgo3LuNLa0lY4bJriZs80wX2qPzdC1uEUkqPdUnl0ZawOAtcrlWzbJs0TiUX6hAsZBPSDW0gTnWSRKliJnMskVFjpSNWCmU4jTos+LE+lbiMtiFPV8ZBoHy9pSCR2+ncs6TNWFMOtvPOEwat95PYslTN8E59FiCNfGlLi91lFeBCkXAHpd3PizGCp3FTkgckdHs8j/udG+7sfBk3xrHv1yxnDuwBluAKlXULCEj7R2KabTMcHj2hOU3AU+gXYP4hwebeT93rv+x8HKDU/TgzYjVrGrs3sxaEhG93uGkKdBeKEYfsYvsh1FH9ZQ3Rd0DNTITXCpj3+ocOS3k+Gt+uycYvMy2P7xw1R5Glv9vEuRUZxdUoSuG9yKFYnrZgN5x8DnSg1HYTn6O7qm9f0eHMY0a80kGtPXmE7RnZkU0tIk+2UE1FoYixoKSDqQ8jJg4IE=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
